image: node:latest

stages:
  - deploy_production

cache:
  paths:
    - node_modules/

Production:
  stage: deploy_production
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - gem install faraday -v 1.8.0
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - master

